package com.opens.datadictionary.solr.models;

import java.io.Serializable;

public class SolrDocumentDto implements Serializable, Cloneable {

	private static final long serialVersionUID = 1L;

	// This will be generated by Mongo
	private String id;

	private String title;

	private String description;

	private String baseUrl;

	private String host;

	ApiResource apiResource;

	ParamDetails paramDetails;

	public SolrDocumentDto() {

	}

	@Override
	public SolrDocumentDto clone() {
		return new SolrDocumentDto(id, title, description, baseUrl, host);
	}

	public SolrDocumentDto(String id, String title, String description, String baseUrl, String host) {
		super();
		this.id = id;
		this.title = title;
		this.description = description;
		this.baseUrl = baseUrl;
		this.host = host;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBaseUrl() {
		return baseUrl;
	}

	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}

	public ApiResource getApiResource() {
		return apiResource;
	}

	public void setApiResource(ApiResource apiResource) {
		this.apiResource = apiResource;
	}

	public ParamDetails getParamDetails() {
		return paramDetails;
	}

	public void setParamDetails(ParamDetails paramDetails) {
		this.paramDetails = paramDetails;
	}

}
