package com.opens.datadictionary.solr.models;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

public class SolrDocumentDto implements Serializable, Cloneable {

	private static final long serialVersionUID = -2337477974806406778L;

	// This will be generated by Mongo

	private String uniqueId;

	private String swaggerDocId;

	private String title;

	private String description;

	private String baseUrl;

	private String host;

	private ApiResource apiResource;

	private Set<String> requestFields = new HashSet<>();

	private Set<String> headerFields = new HashSet<>();

	private Set<String> responseFields = new HashSet<>();

	private String fileName;

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Set<String> getResponseFields() {
		return responseFields;
	}

	public void setResponseFields(Set<String> responseFields) {
		this.responseFields = responseFields;
	}

	public SolrDocumentDto() {

	}

	@Override
	public SolrDocumentDto clone() {
		return new SolrDocumentDto(swaggerDocId, title, description, baseUrl, host, fileName);
	}

	public SolrDocumentDto(String swaggerDocId, String title, String description, String baseUrl, String host,
			String fileName) {
		super();
		this.swaggerDocId = swaggerDocId;
		this.title = title;
		this.description = description;
		this.baseUrl = baseUrl;
		this.host = host;
		this.fileName = fileName;
	}

	public Set<String> getRequestFields() {
		return requestFields;
	}

	public void setRequestFields(Set<String> requestFields) {
		this.requestFields = requestFields;
	}

	public Set<String> getHeaderFields() {
		return headerFields;
	}

	public void setHeaderFields(Set<String> headerFields) {
		this.headerFields = headerFields;
	}

	public String getUniqueId() {
		return uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public String getSwaggerDocId() {
		return swaggerDocId;
	}

	public void setSwaggerDocId(String swaggerDocId) {
		this.swaggerDocId = swaggerDocId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getBaseUrl() {
		return baseUrl;
	}

	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}

	public ApiResource getApiResource() {
		return apiResource;
	}

	public void setApiResource(ApiResource apiResource) {
		this.apiResource = apiResource;
	}

}
